### PR TITLE
Replace BSD-3-Clause license with CC-BY International 4.0

### PR DESCRIPTION
**Pull request by Zeitsperre**
Be sure to add a CC-BY attribution somewhere in each notebook:
```
© Copyright by Ouranos Inc. and {AUTHOR} {YEAR}

This work is licensed under [Creative Commons Attribution 4.0 International](http://creativecommons.org/licenses/by/4.0/)
```

### CODE REVIEW

**Comment by tlogan2000** [comment]
> Be sure to add a CC-BY attribution somewhere in each notebook:
> 
> ```
> © Copyright by Ouranos Inc. and {AUTHOR} {YEAR}
> 
> This work is licensed under [Attribution 4.0 International](http://creativecommons.org/licenses/by/4.0/)
> ```

How would we manage external contribution in this case?  e.g. Someone from UQAM wants to add a notebook?

**Comment by Zeitsperre** [comment]
I imagine it would be:
```
© Copyright by Ouranos Inc. and Joe Yu Kam 2024

This work is licensed under [Creative Commons Attribution 4.0 International](http://creativecommons.org/licenses/by/4.0/)

**Comment by martinleduc** [comment]
> I imagine it would be:
> 
> ```
> © Copyright by Ouranos Inc. and Joe Yu Kam 2024
> 
> This work is licensed under [Creative Commons Attribution 4.0 International](http://creativecommons.org/licenses/by/4.0/)
> ```
> 
> If more people are going to be contributing, it would be good to add an `AUTHORS.md|txt` with people's names and GitHub handles or email addresses.

Does the licence explicitly says that such copyright should appear in every individual notebook or we can refer to a single general copyright for the whole package ?

**Comment by tlogan2000** [comment]
I think one worry that Martin had was that external contributors would be hesitant to contribute if the copyright of thier single notebook belongs, in part, to Ouranos?   I'm not sure i see a way around it but could be a blocker for some

**Comment by Zeitsperre** [comment]
We don't have to include Ouranos if we don't want to. There isn't any direction from above on this; this is what I imagine the direction would want if we consulted them. It's been a while since I've looked at our IP policies.

Given that "we" are maintaining the repo, I think it makes sense to have Ouranos at the repository level. For individual notebooks, we can probably justify that only the original owners have copyright; Any adjustments by us could be considered "donated effort" let's say.

**Comment by Zeitsperre** [comment]
Our IP policy is pretty restrictive, though one could argue that all of our Open Source offerings fail to be covered under this :

### PROPRIÉTÉ INTELLECTUELLE

L’employé cède tous les droits qu’il a, aura ou pourrait avoir relativement à tous les procédés, œuvres, inventions, découvertes, perfectionnement, développement, programmes informatiques, dessins, documents ou autres matières pouvant faire l’objet de droits de propriété intellectuelle créés dans l’exercice de son emploi pour Ouranos.

**Comment by martinleduc** [comment]
I'm still wondering if it is really mandatory to add the copyright to each notebook if there is already one for the whole package. To me this step feels like unnecessary complexity. Since the author names are already in each NB, maybe we could simply add in the readme a "how to cite/use" section to be sure the authors are acknowledged correctly ? Any opinion on this ? @Zeitsperre  @tlogan2000 @huard  ?

**Pull request merged**
